### ISSUE TITLE
change private token to privacy coin on explorer and create pages

### ISSUE THREAD

**Issue by screensav3r** [incognitochain/incognito-web#137]
hi hoai! for top bar and privacy token page on explorer, please change:

Private Tokens -> Privacy Coins
PRIVATE TOKENS -> PRIVACY COINS
Symbol -> Ticker

---

for create tokens page, for everything, please change the word 'token' -> 'coin', 'tokens' -> 'coins' and 'private' -> 'privacy'. 

tokenize is ok, just leave it.

---

for create apps page, please change: 'token' -> 'coin', 'tokens' -> 'coins' 

for privacy/private, please only change the sentence below, the rest is ok:

Integrate private stablecoins -> Integrate privacy stablecoins

---

**Comment by 0xday** [comment]
Will be done by Dec 10, 2019

**Comment by 0xday** [comment]
#139
